version: "3"
services:

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432/tcp

  wordpress:
    image: wordpress
    ports:
      - 8000:80
    networks:
      - frontend

  proxy:
    image: nginx
#    ports:
#      - 6379:80
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: